# You can use this file to create a conda environment for this pipeline:
#   conda create env create -f environment.yml
name: nanoplot-nf-lra
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## basic packages
  - pigz=2.3.4

  ## bioconda packages, see above
  - nanoplot=1.30.1
  - psutil
